### ISSUE TITLE
Assay types are not fully centralized

### ISSUE THREAD

**Issue by wasade** [jdereus/LabControl#480]
While flipping through pages, I noticed that "NewKindOfAssay" is an assay type in a test environment (added [here](https://github.com/jdereus/labman/blob/a24d46cd0a65b02d4c766f212e9e1b191fedf9e6/labcontrol/db/support_files/populate_test_db.sql#L891)). However, it is not valid across the system as it is still accessible and can result in exceptions. 

I'm marking this as a nice to have issue right now as I believe we can defer the refactor since I don't believe we're adding in new assays near term. However, we probably only want to present valid assays to users.

![assay_is_not_controlled](https://user-images.githubusercontent.com/474290/56619869-ea9e5900-65db-11e9-9f53-3a1f34a76c94.gif)

```bash
AN ERROR HAS OCCURED!
Please copy the following into an issue in our github repository

Error
Unrecognized assay type: NewKindOfAssay

Traceback
Traceback (most recent call last): 
File "/Users/dtmcdonald/miniconda3/envs/labcontrol/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/Users/dtmcdonald/miniconda3/envs/labcontrol/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper return method(self, *args, **kwargs) 
File "/Users/dtmcdonald/ResearchWork/software/labman/labcontrol/gui/handlers/process_handlers/sequencing_process.py", line 59, in get text = process.generate_sample_sheet() 
File "/Users/dtmcdonald/ResearchWork/software/labman/labcontrol/db/process.py", line 3242, in generate_sample_sheet raise ValueError("Unrecognized assay type: {0}".format(assay)) 
ValueError: Unrecognized assay type: NewKindOfAssay 
```

**Comment by charles-cowart** [comment]
Resolved with #554
