### ISSUE TITLE
Can't enter sample info for project 12604

### ISSUE THREAD

**Issue by jtoronczak** [jdereus/LabControl#558]
In Qiita we've selected for the tube id to be input into the platemap, and once the samples are pasted into the plate map (using tube id) in this error shows up:

Error
Error running SQL query: Query: SELECT sample_values->'tube_id' FROM qiita.sample_12604 as tube_id WHERE sample_id = %s Arguments: ['12604.MAD.1.17.268.01'] Error: permission denied for relation sample_12604

Traceback
Traceback (most recent call last): 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 586, in _execute cur.execute(sql, sql_args) 
File "/home/labcontrol/miniconda3/envs/labcontrol2019.6.1/lib/python3.5/site-packages/psycopg2/extras.py", line 142, in execute return super(DictCursor, self).execute(query, vars) 
psycopg2.errors.InsufficientPrivilege: permission denied for relation sample_12604 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/home/labcontrol/miniconda3/envs/labcontrol2019.6.1/lib/python3.5/site-packages/tornado/web.py", line 1590, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/home/labcontrol/miniconda3/envs/labcontrol2019.6.1/lib/python3.5/site-packages/tornado/web.py", line 3006, in wrapper return method(self, *args, **kwargs) 
File "/home/labcontrol/labcontrol/labman/labcontrol/gui/handlers/plate.py", line 267, in get self.write(json_encode(plate_layout_handler_get_request(plate_id))) 
File "/home/labcontrol/labcontrol/labman/labcontrol/gui/handlers/plate.py", line 256, in plate_layout_handler_get_request sample = composition.specimen_id 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/composition.py", line 582, in specimen_id return study.sample_id_to_specimen_id(self.sample_id) 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/study.py", line 177, in sample_id_to_specimen_id res = TRN.execute_fetchflatten() 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 735, in execute_fetchflatten return list(chain.from_iterable(self.execute()[idx])) 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 643, in execute return self._execute() 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 590, in _execute self._raise_execution_error(sql, sql_args, e) 
File "/home/labcontrol/labcontrol/labman/labcontrol/db/sql_connection.py", line 535, in _raise_execution_error % (sql, str(sql_args), str(error))) 
ValueError: Error running SQL query: Query: SELECT sample_values->'tube_id' FROM qiita.sample_12604 as tube_id WHERE sample_id = %s Arguments: ['12604.MAD.1.17.268.01'] Error: permission denied for relation sample_12604 

Request Info
uri: /plate/251/layout
host: labcontrol.ucsd.edu
body_arguments: {}
body: b''
headers: Cookie: _ga=GA1.2.515592774.1562178083; jlinkauthserver=findlay; __utmc=57960238; jlinkserver=act; jssoserver=findlay; _fbp=fb.1.1562618242476.53653934; user=2|1:0|10:1563385655|4:user|28:Imp0b3JvbmN6YWtAdWNzZC5lZHUi|6375bf15df215358c0f5a69dfb4dbb3b5e3b671beb149d0c2db5f2c87f4e4eb7; __utma=57960238.515592774.1562178083.1562682506.1563890447.3; __utmz=57960238.1563890447.3.3.utmcsr=a5.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO; jlinksessionidx=z7790792b2ece3298735a8a3888893b37; xjlinkloginMyTimeEntry.User=REMOVE; jlinkappx=/marketplace-sso/signon; xjlinkloginStaff.InquiryA4=OK; jlinkpedjat=pedjat X-Real-Ip: 137.110.66.21 Accept-Encoding: identity Accept: */* Accept-Language: en-US,en;q=0.9 Host: labcontrol.ucsd.edu X-Requested-With: XMLHttpRequest User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Connection: upgrade Referer: https://labcontrol.ucsd.edu/plate?process_id=309 X-Forwarded-For: 137.110.66.21 
protocol: https
_finish_time: None
_cookies: Set-Cookie: __utma=57960238.515592774.1562178083.1562682506.1563890447.3 Set-Cookie: __utmc=57960238 Set-Cookie: __utmz="57960238.1563890447.3.3.utmcsr=a5.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO" Set-Cookie: _fbp=fb.1.1562618242476.53653934 Set-Cookie: _ga=GA1.2.515592774.1562178083 Set-Cookie: jlinkappx="/marketplace-sso/signon" Set-Cookie: jlinkauthserver=findlay Set-Cookie: jlinkpedjat=pedjat Set-Cookie: jlinkserver=act Set-Cookie: jlinksessionidx=z7790792b2ece3298735a8a3888893b37 Set-Cookie: jssoserver=findlay Set-Cookie: user=2|1:0|10:1563385655|4:user|28:Imp0b3JvbmN6YWtAdWNzZC5lZHUi|6375bf15df215358c0f5a69dfb4dbb3b5e3b671beb149d0c2db5f2c87f4e4eb7 Set-Cookie: xjlinkloginMyTimeEntry.User=REMOVE Set-Cookie: xjlinkloginStaff.InquiryA4=OK
server_connection: 
query_arguments: {}
version: HTTP/1.1
arguments: {}
method: GET
host_name: labcontrol.ucsd.edu
path: /plate/251/layout
connection: 
files: {}
remote_ip: 127.0.0.1
_start_time: 1565102063.703464
query:

**Comment by charles-cowart** [comment]
Hi Julia,

Thanks for the bug report! We've already fixed some of the code in this
area, so this will be a perfect to use as a use case!

Best,

Charlie

**Comment by jtoronczak** [comment]
Hi Charlie,

thanks for getting back to me! I'm not entirely sure what that means, but
I've also had issues in the last few plates (Alderete: 12604) and (Twins
UK: 11624) with none of the samples matching the qiita project.

Best,
Julia

**Comment by charles-cowart** [comment]
@fedarko Adding you to this, as this will be a useful sample test case once code is pushed to maptest.ucsd.edu, and we get access to the study data required to debug this.
